# Generated by Django 6.0.5 on 2026-06-01 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guige_leixing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规格类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品规格类型',
                'verbose_name_plural': '商品规格类型',
            },
        ),
        migrations.CreateModel(
            name='Guige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规格')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('guige_leixing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.guige_leixing', verbose_name='规格类型id')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
            },
        ),
        migrations.AddField(
            model_name='shangpin',
            name='guige_leixing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.guige_leixing', verbose_name='规格类型'),
        ),
    ]
