# Generated by Django 6.0.5 on 2026-06-01 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_guige_leixing_guige_shangpin_guige_leixing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detail_images/', verbose_name='详情图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sort', models.IntegerField(default=0, verbose_name='排序（数字越小越靠前）')),
                ('shangpin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_images', to='goods.shangpin', verbose_name='关联商品')),
            ],
            options={
                'verbose_name': '商品详情图片',
                'verbose_name_plural': '商品详情图片',
                'db_table': 'tb_goods_detail_image',
                'ordering': ['sort'],
            },
        ),
    ]
