# Generated by Django 6.0.6 on 2026-06-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goodsdetailimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='购买数量')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('shangpin_id', models.IntegerField(verbose_name='商品ID')),
                ('guige_id', models.IntegerField(blank=True, null=True, verbose_name='规格ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'tb_cartinfo',
            },
        ),
    ]
