# Generated by Django 6.0.6 on 2026-06-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_cartinfos'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(verbose_name='订单总价')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('state', models.CharField(choices=[('待支付', '待支付'), ('已支付', '已支付'), ('发货中', '发货中'), ('已签收', '已签收'), ('退货中', '退货中')], max_length=20, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
    ]
